name: Deploy to Neocities

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2' # You can use another version if needed

    - name: Install Neocities CLI
      run: gem install neocities

    - name: Deploy to Neocities
      env:
        NEOCITIES_API_KEY: ${{ secrets.NEOCITIES_API_KEY }}
      run: |
        echo "${NEOCITIES_API_KEY}" > ~/.config/neocities/config
        neocities push .
